version: "4.29.0"
services:
  app_service:
    container_name: app_gestlaboratorios_cont
    image: gestlaboratorios_img:1.0.0
    build:
      context: .
    ports:
      - '8086:8080'
    networks:
      TFG_network:
        ipv4_address: 192.168.0.3
    environment:
      - BD_PostgreSQL=jdbc:postgresql://conexionPostgreSQL_service/laboratoriosdb
      - USUARIO_PostgreSQL=i42rocrr
      - PASSWORD_PostgreSQL=Oca.14005
    depends_on:
      - conexionPostgreSQL_service
  conexionPostgreSQL_service:
    image: postgres
    container_name: postgresql_gestlaboratorios_cont
    ports:
      - 5433:5432
    expose:
      - "5433"
    environment:
      - POSTGRES_DB=laboratoriosdb
      - POSTGRES_USER=i42rocrr
      - POSTGRES_PASSWORD=Oca.14005
    volumes:
      - ../../Recursos/Volumenes/Vol_PostgreSQL:/var/lib/postgresql/data
    networks:
      TFG_network:
        ipv4_address: 192.168.0.2
    hostname: postgresqlserver
networks:
  TFG_network:
    name: TFG_net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1